### ISSUE TITLE
Tabs are unclickable with TST3.4

### ISSUE THREAD

**Issue by nicknovik** [Lej77/move-unloaded-tabs-for-tree-style-tab#4] opened 2020-03-08 20:08 UTC
Systems:
Windows 10E-64.0.1.02_2019 and Ubuntu 18.4.03 LTS
FF 73.0.1 on both

Steps:
1) Make sure TST3.4 and "Move unloaded tabs for Tree Style Tab" 2.3 is installed
2) open more than one tab (in my case it's 30 on windows and about 100 on Ubuntu)
3) Click on any tab which is not the current one

Problem:
 Tab is not activated

Expected:
 Tab becomes active when user clicks on it.

Observations:
- Drag&drop of tabs within TST works fine.
- Switching between tabs with Ctrl+Tab or Ctrl+PgUp/PgDown works find.
- Clicking on web pages, "new tab" button at the bottom of TST, or any other place in browser works fine.
- Right-click and middle-click on tabs work fine.
- When "Move unloaded tabs for Tree Style Tab" is deactivated, behavior is restored to normal (tabs become active on clicking)

**Comment by Lej77** [comment] 2020-03-08 20:38
These looks like the same as issue #3 and is caused by a change in [Tree Style Tab's addon API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons) regarding its `tab-mousedown`, `tab-mouseup` and `tab-clicked` notifications. It no longer sends the `tab-mouseup` event as it did before when the `tab-mousedown` event handler attempts to delay or cancel Tree Style Tab's default action. 

As mentioned in the other issue this will be fixed in Tree Style Tab v3.4.4. Anyways this extension isn't really needed on later versions of Tree Style Tab since it has changed its default behavior to not select/active/load tabs when they are moved and therefore you should probably just uninstall this extension.

**Closed as completed** 2024-01-10 20:37 UTC
Labels: duplicate
